topics = [
    "Units of measurements",
    "System of units",
    "SI Units",
    "Fundamental and derived units",
    "Least count",
    "Significant figures",
    "Errors in measurements",
    "Dimensions of Physics quantities",
    "Dimensional analysis and its applications",
    "The frame of reference",
    "Motion in a straight line",
    "Speed and velocity",
    "Uniform and non-uniform motion",
    "Average speed and instantaneous velocity",
    "Uniformly accelerated motion",
    "Velocity-time",
    "Position-time graph",
    "Relations for uniformly accelerated motion",
    "Relative velocity",
    "Motion in a plane",
    "Projectile motion",
    "Uniform circular motion",
    "Force and inertia",
    "Newton’s first law of motion",
    "Momentum",
    "Newton’s second law of motion",
    "Impulse",
    "Newton’s third Law of motion",
    "Law of conservation of linear momentum and its applications",
    "Equilibrium of concurrent forces",
    "Static and Kinetic friction",
    "Laws of friction",
    "Rolling friction",
    "Dynamics of uniform circular motion",
    "Centripetal force and its applications: vehicle on a level circular road, vehicle on a banked road",
    "Work done by a constant force and a variable force",
    "Kinetic and potential energies",
    "Work-energy theorem",
    "Power",
    "The potential energy of a spring",
    "Conservation of mechanical energy",
    "Conservative and non-conservative forces",
    "Motion in a vertical circle",
    "Elastic and inelastic collisions in one and two dimensions",
    "Centre of mass of a two-particle system",
    "Centre of mass of a rigid body",
    "Basic concepts of rotational motion",
    "Moment of a force",
    "Torque",
    "Angular momentum",
    "Conservation of angular momentum and its applications",
    "The moment of inertia",
    "The radius of gyration",
    "Values of moments of inertia for simple geometrical objects",
    "Parallel and perpendicular axes theorems and their applications",
    "Equilibrium of rigid bodies",
    "Rigid body rotation and equations of rotational motion",
    "Comparison of linear and rotational motions",
    "The universal law of gravitation",
    "Acceleration due to gravity and its variation with altitude and depth",
    "Kepler’s law of planetary motion",
    "Gravitational potential energy",
    "Gravitational potential",
    "Escape velocity",
    "Motion of a satellite",
    "Orbital velocity",
    "Time period and energy of satellite",
    "Elastic behaviour",
    "Stress-strain relationship",
    "Hooke's Law",
    "Young's modulus",
    "Bulk modulus",
    "Modulus of rigidity",
    "Pressure due to a fluid column",
    "Pascal's law and its applications",
    "Effect of gravity on fluid pressure",
    "Viscosity",
    "Stoke’s law",
    "Terminal velocity",
    "Streamline and turbulent flow",
    "Critical velocity",
    "Bernoulli’s principle and its applications",
    "Surface energy and surface tension",
    "Angle of contact",
    "Excess of pressure across a curved surface",
    "Application of surface tension: drops, bubbles and capillary rise",
    "Heat",
    "Temperature",
    "Thermal expansion",
    "Specific heat capacity",
    "Calorimetry",
    "Change of state",
    "Latent heat",
    "Heat transfer: conduction, convection and radiation",
    "Thermal equilibrium and the concept of temperature",
    "Zeroth law of thermodynamics",
    "Heat",
    "Work and internal energy",
    "The first law of thermodynamics",
    "Isothermal and adiabatic processes",
    "The second law of thermodynamics: reversible and irreversible processes",
    "Equation of state of a perfect gas",
    "Work done on compressing a gas",
    "Kinetic theory of gases: assumptions",
    "The concept of pressure",
    "Kinetic interpretation of temperature",
    "RMS speed of gas molecules",
    "Degrees of freedom",
    "Law of equipartition of energy and applications to specific heat capacities of gases",
    "Mean free path",
    "Avogadro’s number",
    "Oscillations and periodic motion: time period, frequency, displacement as a function of time, periodic functions",
    "Simple harmonic motion (S.H.M.) and its equation",
    "Phase",
    "Oscillations of a spring: restoring force and force constant",
    "Energy in S.H.M.: kinetic and potential energies",
    "Simple pendulum: derivation of expression for its time period",
    "Wave motion",
    "Longitudinal and transverse waves",
    "Speed of the travelling wave",
    "Displacement relation for a progressive wave",
    "Principle of superposition of waves",
    "Reflection of waves",
    "Standing waves in strings and organ pipes",
    "Resonance of musical instruments",
    "Beats",
    "Doppler effect"
]
