physics_syllabus = [
    
    "Conservation of charge",
    "Coulomb's law forces between two point charges",
    "Forces between multiple charges",
    "Superposition principle",
    "Continuous charge distribution",
    "Electric field due to a point charge",
    "Electric field lines",
    "Electric dipole",
    "Electric field due to a dipole",
    "Torque on a dipole in a uniform electric field",
    "Electric flux",
    "Gauss's law and its applications to find field due to infinitely long uniformly charged straight wire",
    "Field due to uniformly charged infinite plane sheet",
    "Field due to uniformly charged thin spherical shell",
    "Electric potential and its calculation for a point charge",
    "Electric potential of electric dipole and system of charges",
    "Potential difference",
    "Equipotential surfaces",
    "Electrical potential energy of a system of two point charges",
    "Electrical potential energy of electric dipole in electrostatic field",
    "Conductors and insulators",
    "Dielectrics and electric polarization",
    "Capacitors and capacitance",
    "Combination of capacitors in series and parallel",
    "Capacitance of a parallel plate capacitor with and without dielectric medium",
    "Energy stored in a capacitor",

    
    "Drift velocity",
    "Mobility and their relation with electric current",
    "Ohm's law",
    "Electrical resistance",
    "I-V characteristics of Ohmic conductors",
    "I-V characteristics of Non-ohmic conductors",
    "Electrical energy and power",
    "Electrical resistivity",
    "Electrical conductivity",
    "Series and parallel combinations of resistors",
    "Temperature dependence of resistance",
    "Internal resistance",
    "Potential difference and emf of a cell",
    "Combination of cells in series and parallel",
    "Kirchhoff’s laws and their applications",
    "Wheatstone Bridge",
    "Meter Bridge",

    "Biot - Savart law and its application to the current carrying circular loop",
    "Ampere's law and its applications to infinitely long current carrying straight wire and solenoid",
    "Force on a moving charge in a uniform magnetic and electric field",
    "Force on a current-carrying conductor in a uniform magnetic field",
    "Force between two parallel current-carrying conductors-definition of ampere",
    "Torque experienced by a current loop in a uniform magnetic field",
    "Moving coil galvanometer, its sensitivity and conversion to ammeter and voltmeter",
    "Current loop as a magnetic dipole and its magnetic dipole moment",
    "Bar magnet as an equivalent solenoid",
    "Magnetic field lines",
    "Magnetic field due to a magnetic dipole (bar magnet) along its axis and perpendicular to its axis",
    "Torque on a magnetic dipole in a uniform magnetic field",
    "Para-, dia- and ferro-magnetic substances with examples",
    "Effect of temperature on magnetic properties",

    
    "Faraday's law",
    "Induced emf and current",
    "Lenz’s law",
    "Eddy currents",
    "Self and mutual inductance",
    "Alternating currents",
    "Peak and RMS value of alternating current/voltage",
    "Reactance and impedance",
    "LCR series circuit",
    "Resonance, power in AC circuits",
    "Wattless current",
    "AC generator and transformer",

    
    "Displacement current",
    "Electromagnetic waves and their characteristics",
    "Transverse nature of electromagnetic waves",
    "Electromagnetic spectrum (radio waves, microwaves, infrared, visible, ultraviolet, X-rays, Gamma rays)",
    "Applications of electromagnetic waves",

    
    "Reflection of light",
    "Spherical mirrors",
    "Mirror formula",
    "Refraction of light at plane and spherical surfaces",
    "Thin lens formula and lens maker formula",
    "Total internal reflection and its applications",
    "Magnification",
    "Power of a lens",
    "Combination of thin lenses in contact",
    "Refraction of light through a prism",
    "Microscope and astronomical telescope (reflecting and refracting) and their magnifying powers",
    "Wave optics: wavefront and Huygens' Principle",
    "Laws of reflection and refraction using Huygens principle",
    "Interference: Young's double-slit experiment and expression for fringe width",
    "Coherent sources and sustained interference of light",
    "Diffraction due to a single slit, width of central maximum",
    "Polarization: plane-polarized light",
    "Brewster’s law",
    "Uses of plane-polarized light and Polaroid",

    
    "Dual nature of radiation",
    "Photoelectric effect",
    "Hertz and Lenard's observations",
    "Einstein's photoelectric equation",
    "Particle nature of light",
    "Matter waves: wave nature of particle",
    "de Broglie relation",

   
    "Alpha-particle scattering experiment",
    "Rutherford's model of atom",
    "Bohr model",
    "Energy levels",
    "Hydrogen spectrum",
    "Composition and size of nucleus",
    "Atomic masses",
    "Mass-energy relation",
    "Mass defect",
    "Binding energy per nucleon and its variation with mass number",
    "Nuclear fission and fusion",

   
    "Semiconductors",
    "Semiconductor diode: I-V characteristics in forward and reverse bias",
    "Diode as a rectifier",
    "I-V characteristics of LED",
    "Photodiode",
    "Solar cell",
    "Zener diode",
    "Zener diode as a voltage regulator",
    "Logic gates (OR, AND, NOT and NAND, NOR)"
]
